import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import RaceCard from "../../../../components/RaceCard";
// import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "@/utils/api";
import BuildCard from "@/components/BuildCard";
// import { useState } from "react";

const FindBuilds: NextPage = () => {
  const { raceName, opponentRace } = useRouter().query as {
    opponentRace: string;
    raceName: string;
  };
  const builds = api.builds.getBuildsByMatchUp.useQuery({
    matchUp: `${raceName?.toLowerCase().charAt(0)}v${opponentRace
      ?.toLowerCase()
      .charAt(0)}`,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white dark:bg-gray-800  dark:text-white px-4">
        <h1>
          {raceName} vs {opponentRace}
        </h1>
        <div className="grid grid-cols-3 gap-4 w-full max-w-7xl">
          {builds.data?.map((build) => (
            <BuildCard key={build.id} build={build} />
          ))}
        </div>
      </main>
    </>
  );
};

export default FindBuilds;
