import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import RaceCard from "../../../../components/RaceCard";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
// import { useState } from "react";

const FindBuilds: NextPage = () => {
  const { raceName } = useRouter().query;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white dark:bg-gray-800  dark:text-white">
        <div className="flex flex-col text-center ">
          <p>{raceName}</p>
          <p>VS.</p>
          <p>Select Opponent&apos;s Race</p>
        </div>
        <ul className="grid grid-cols-3 gap-4">
          <li>
            <RaceCard
              href={`/races/${raceName as string}/match-ups/zerg`}
              raceImageSrc={"/zerg.webp"}
              raceName="Zerg"
              isOpponent
            />
          </li>
          <li>
            <RaceCard
              href={`/races/${raceName as string}/match-ups/terran`}
              raceImageSrc={"/terran.webp"}
              raceName="Terran"
              isOpponent
            />
          </li>
          <li>
            <RaceCard
              href={`/races/${raceName as string}/match-ups/protoss`}
              raceImageSrc={"/protoss.jpg"}
              raceName="Protoss"
              isOpponent
            />
          </li>
        </ul>
      </main>
    </>
  );
};

export default FindBuilds;
