import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
// import { useState } from "react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-white   dark:bg-gray-800">
        <h1>Welcome to SC2 Build Order Manager</h1>
        <Link href="/submit-build" className="link">
          Submit a new Build
        </Link>
        <Link href="/builds" className="races">
          {" "}
          View Builds
        </Link>
      </main>
    </>
  );
};

export default Home;
