import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import RaceCard from "../components/RaceCard";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
// import { useState } from "react";

const matchUps = [
  {
    matchUp: "zvt",
    yourRace: "Zerg",
    opponentRace: "Terran",
  },
  {
    matchUp: "zvp",
    yourRace: "Zerg",
    opponentRace: "Protoss",
  },
  {
    matchUp: "zvz",
    yourRace: "Zerg",
    opponentRace: "Zerg",
  },

  {
    matchUp: "tvp",
    yourRace: "Terran",
    opponentRace: "Protoss",
  },
  {
    matchUp: "tvz",
    yourRace: "Terran",
    opponentRace: "Zerg",
  },
];

const FindBuilds: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center gap-4 p-8 pt-12 text-white dark:bg-gray-800  dark:text-white">
        <h1>Select a Match Up</h1>
        <ul className="grid grid-cols-3 gap-4">
          {matchUps.map((matchUp) => (
            <li key={matchUp.matchUp}>
              <RaceCard
                matchUp={matchUp.matchUp}
                href={`
                  /races/${matchUp.yourRace.toLowerCase()}/match-ups/${matchUp.opponentRace.toLowerCase()}
                `}
                raceImageSrc={"/zerg.webp"}
                raceName={`${matchUp.yourRace} vs ${matchUp.opponentRace}`}
              />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default FindBuilds;
