import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import RaceCard from "../components/RaceCard";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "../utils/api";
// import { useState } from "react";

const FindBuilds: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white dark:bg-gray-800  dark:text-white">
        <h1>Select your Race</h1>
        <ul className="grid grid-cols-3 gap-4">
          <li>
            <RaceCard
              href={`/races/zerg/match-ups`}
              raceImageSrc={"/zerg.webp"}
              raceName="Zerg"
            />
          </li>
          <li>
            <RaceCard
              href={`/races/terran/match-ups`}
              raceImageSrc={"/terran.webp"}
              raceName="Terran"
            />
          </li>
          <li>
            <RaceCard
              href={`/races/protoss/match-ups`}
              raceImageSrc={"/protoss.jpg"}
              raceName="Protoss"
            />
          </li>
        </ul>
      </main>
    </>
  );
};

export default FindBuilds;
