import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import { useState } from "react";
import { useRouter } from "next/router";

const SubmitBuildPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();

  const [buildOrder, setBuildOrder] = useState("");
  const [matchUp, setMatchUp] = useState("zvt");

  const router = useRouter();

  const handleSubmitBuildOrder = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await createBuildMutation.mutateAsync({
        matchUp,
        buildOrder,
      });
    } catch (error) {
      console.log(error);
    }
    router.push("/builds");
  };

  return (
    <>
      <Head>
        <title>Submit a build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Submit a build order</h1>
        <form className="flex flex-col gap-4" onSubmit={handleSubmitBuildOrder}>
          <label htmlFor="match-up-select">Match Up</label>
          <select
            className="text-black"
            value={matchUp}
            onChange={(e) => setMatchUp(e.target.value)}
            name=""
            id="match-up-select"
            required
          >
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>
          </select>

          <textarea
            className="required p-2 text-black"
            value={buildOrder}
            onChange={(e) => setBuildOrder(e.target.value)}
          />
          <button className="mt-2 bg-white p-2 text-black" type="submit">
            Search
          </button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuildPage;
