import { type NextPage } from "next";
import Head from "next/head";

import { useRouter } from "next/router";

import { api } from "@/utils/api";




const BuildPage: NextPage = () => {
  const { buildId } = useRouter().query as {
    buildId: string;
  };
  const build = api.builds.getBuildsById.useQuery({
    buildId,
  });

  return (
    <>
      <Head>
        <title>View Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container m-auto flex flex-col gap-4 bg-gray-800 px-12 pt-12">
        <h1 className="text-2xl text-white">{build?.data?.title}</h1>
        <p className="bg-gray-500 p-4">{build.data?.buildOrder}</p>
      </main>
    </>
  );
};

export default BuildPage;
